# .zshenv is always sourced

#
# Path
#

export PATH=$PATH:/usr/libexec
export PATH=$PATH:/usr/X11/bin
export PATH=/usr/local/sbin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH

#
# Node.js
#

export NODE_PATH=/usr/local/lib/node_modules
export PATH=/usr/local/share/npm/bin:$PATH
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

#
# Editor
#

export EDITOR="lvim"

#
# Go
#

if [ -e $HOME/.segment ] ; then
  export GOPATH=$HOME/dev
else
  export GOPATH=$HOME/go
fi
export PATH=$GOPATH/bin:$PATH
export PATH=/usr/local/opt/go/libexec/bin:$PATH
export GOPRIVATE=github.com/segment*

#
# Python
#

export PATH=$PATH:/opt/homebrew/opt/python@3.9/libexec/bin

#
# Rust
#

source "$HOME/.cargo/env"

#
# Segment
#

if [ -e $HOME/.segment ] ; then
# BEGIN GOLANG CONFIGURATION
export GOPATH="$HOME/dev"
export PATH="$PATH:$GOPATH/bin"
source "$GOPATH/src/github.com/segmentio/dotfiles/index.sh"
# END GOLANG CONFIGURATION
# BEGIN SEGMENT_TEAM DEFINITION
export SEGMENT_TEAM="foundation"
# END SEGMENT_TEAM DEFINITION
# BEGIN LAPTOP SETUP CONFIG PATH INCLUDE
export PATH="$PATH:/Users/tysonmote/dev/src/github.com/segmentio/engineering-laptop-setup/bin"
# END LAPTOP SETUP CONFIG PATH INCLUDE
fi
