# .zshrc is sourced for interactive shells only

# -- ZSH

# emacs-style keybindings
bindkey -e
# long history
HISTSIZE=1000
SAVEHIST=10000
# additional completions
fpath+=~/.zfunc

# -- oh-my-zsh

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
DEFAULT_USER=`whoami`
ENABLE_CORRECTION="false"
DISABLE_AUTO_UPDATE=true
plugins=(brew golang rust cargo)
source $ZSH/oh-my-zsh.sh

# -- fzf

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --exclude vendor'

# -- git

alias gpr='git push -u origin `git rev-parse --abbrev-ref HEAD` ; hub pull-request'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gb='git branch'
alias gs='git status'

# -- Ruby

export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"
alias rake='noglob rake'
alias be="bundle exec"

# -- Node.js / NVM

export NVM_DIR="$HOME/.nvm"
loadnvm() {
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
}

# -- Rust

export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"

# -- Tab completion

zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
source /usr/local/share/zsh/site-functions/_aws   # awscli

# -- Packer / ec2-ami-tools stuff

export JAVA_HOME="$(/usr/libexec/java_home)"
export EC2_AMITOOL_HOME="$(find /usr/local/Cellar/ec2-ami-tools/*/libexec -type d | head -n 1)"
export EC2_HOME=$EC2_AMITOOL_HOME

# -- Segment dotfiles

segment_dotfiles=(docker general robo scripts vm)
for dotfile in $segment_dotfiles ; do
  source $HOME/dev/src/github.com/segmentio/dotfiles/source/$dotfile.sh
done

# Production
alias t='robo prod.tool'
alias wt='robo prod warehouse-tool'
alias rt='robo prod routing-tool'
alias awsprod='aws-okta exec prod-privileged -- aws'
alias logsprod='aws-okta exec production -- s3logs'
alias s3prod='aws-okta exec prod-privileged -- aws s3'
# Staging
alias awsstage='aws-okta exec stage-privileged -- aws'
alias logsstage='aws-okta exec stage -- s3logs'
alias s3stage='aws-okta exec stage-privileged -- aws s3'

# -- Secrets

[ -f $HOME/.secrets/prod ] && source $HOME/.secrets/prod

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
